[package]
name = "yane_desktop"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yane_core = { path = "../yane-core" }
simple = "0.3.0"